# Import necessary packages

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os

import DiadFit as pf
pf.__version__

'1.0.17'

# Setup the folder access and paths

In [2]:
if os.name=='posix':
    slash='/'
else:
    slash='\\'

MasterFolder=os.path.dirname(os.path.dirname(os.getcwd()))

# #Folder to save figures

# figpath=MasterFolder +slash+'Figs'
# if not os.path.exists(figpath):
#     os.mkdir(figpath)

# #Folder to save full datasets

compilation_folder=MasterFolder +slash+"Data_processing_notebooks"+slash+'Data_processing_Ulu_mounts'+slash+'Notebook_Compiled_data'
if not os.path.exists(compilation_folder):
    os.mkdir(compilation_folder)

# This compiles all the Raman data into one file, and exports

## First create the function

In [3]:


## This function compiles raman sessions found in the master folder (even in subdirectories of the specified folder)

def compile_Raman_sessions(*, path=None, sheet_name='Sheet1', keyword='Raman_session'):
    df = pd.DataFrame()

    for root, dirs, files in os.walk(path):
        for file in files:
            if keyword in file and file.endswith('.xlsx'):
                print(file)
                file_path = os.path.join(root, file)
                sheets = pd.read_excel(file_path, sheet_name)
                df = pd.concat([df, sheets], axis=0, ignore_index=True)
                unnamed_columns = [col for col in df.columns if 'Unnamed' in col]
                df = df.drop(columns=unnamed_columns)

    return df

## Now run the function

In [4]:
Ulu = compile_Raman_sessions(path=MasterFolder+slash+"Data"+slash+"Data_Ulu_mounts"+slash+"Raman",sheet_name='Sheet1',keyword='Raman_session')

Raman_session_March 7, 2025_fitted_2025-03-11.xlsx
Raman_session_March 20, 2025_fitted_2025-03-20.xlsx
Raman_session_March 18, 2025_fitted_2025-03-20.xlsx
Raman_session_March 17, 2025_fitted_2025-03-20.xlsx
Raman_session_March 21, 2025_fitted_2025-03-25.xlsx
Raman_session_April 8, 2025_fitted_2025-04-09.xlsx
Raman_session_April 1, 2025_fitted_2025-04-09.xlsx
Raman_session_April 9, 2025_fitted_2025-04-10.xlsx
Raman_session_April 10, 2025_fitted_2025-04-11.xlsx

# Now let's tidy names and filter bad analyses before exporting

In [5]:
# filter out bad ones. Including one standard that drifted. 
Ulu = Ulu[(~Ulu['filename'].str.contains('test|end_r4'))&(Ulu['Density g/cm3']>0)&~(Ulu['σ Density g/cm3']>0.04)]

Ulu['date_object']=pd.to_datetime(Ulu['date'])

Ulu=Ulu.sort_values(by=['date_object', 'filename'])


# def transform_name(name):
#     # Check if the name starts with 'KL0919'
#     if name.startswith('KL0919'):
#         # Replace 'KL0919' with '919' and replace '-' with '_'
#         new_name = '919' + name[6:].replace('-', '_')
#     else:
#         # Replace '-' with '_'
#         new_name = name.replace('-', '_')
#     return new_name
# # Apply the transformation to the column
# Ulu['consistent_name'] = Ulu['filename'].apply(transform_name)

Ulu=Ulu.reset_index(drop=True)

# Ulu['filename_4merge'] = Ulu['filename'] + '_index' + Ulu.index.astype(str)
# Ulu['consistent_name_4merge'] = Ulu['consistent_name'] + '_index' + Ulu.index.astype(str)

Ulu.to_clipboard(excel=True, index=False)

Ulu.to_excel(compilation_folder+'/'+"Ulu_Raman_allreps.xlsx")

Ulu

,filename,Density g/cm3,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),σ Density g/cm3 (from densimeter),Corrected_Splitting,Corrected_Splitting_σ,Corrected_Splitting_σ_Ne,Corrected_Splitting_σ_peak_fit,power (mW),...,Model_name_y,Carb_Diad_Ratio,SO2_Diad_Ratio,SO2_mol_ratio,time,preferred_values,lower_values,upper_values,Model_name,date_object
0,FG04-A1-4_end-rep4,0.691120,0.002862,0.001573,0.002391,104.328535,0.003087,0.000529,0.003048,5.994,...,Spline,0.036078,NaN,NaN,64007.0,0.997848,0.997843,0.997853,NaN,2025-03-07
1,FG04-A1-4_end-rep5,0.701827,0.002909,0.001653,0.002394,104.349488,0.003226,0.000531,0.003189,5.996,...,NaN,NaN,NaN,NaN,64409.0,0.997849,0.997843,0.997854,NaN,2025-03-07
2,FG04-A1-4_end-rep6,0.694049,0.002787,0.001431,0.002392,104.334278,0.002803,0.000533,0.002758,6.010,...,NaN,NaN,NaN,NaN,64679.0,0.997849,0.997844,0.997854,NaN,2025-03-07
3,FG04-A1-4_start-rep1,0.690485,0.004501,0.003814,0.002391,104.327289,0.007486,0.000517,0.007484,5.987,...,NaN,NaN,NaN,NaN,37384.0,0.997888,0.997883,0.997893,NaN,2025-03-07
4,FG04-A1-4_start-rep2,0.693988,0.004277,0.003546,0.002392,104.334157,0.006949,0.000515,0.006944,5.950,...,NaN,NaN,NaN,NaN,37683.0,0.997887,0.997882,0.997892,NaN,2025-03-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,KL0930_c312_a1_FIA,0.194130,0.002636,0.001158,0.002368,103.228909,0.002836,0.000663,0.002763,5.990,...,NaN,NaN,NaN,NaN,43865.0,0.997867,0.997861,0.997874,NaN,2025-04-10
223,KL0930_c312_a2_FIB,0.153764,0.006101,0.004682,0.003912,103.138312,0.011816,0.000661,0.011822,5.994,...,NaN,NaN,NaN,NaN,44244.0,0.997866,0.997859,0.997872,NaN,2025-04-10
224,KL0930_c318_a1_FIA,0.119719,0.003993,0.001138,0.003827,103.052394,0.002872,0.000666,0.002800,10.008,...,NaN,NaN,NaN,NaN,42323.0,0.997875,0.997868,0.997881,NaN,2025-04-10
225,KL0930_c321_a1_FIA,0.165620,0.007694,0.006600,0.003954,103.168233,0.016657,0.000672,0.016679,9.985,...,NaN,NaN,NaN,NaN,41011.0,0.997882,0.997876,0.997889,NaN,2025-04-10
226,KL0930_c321_a2_FIB,0.191143,0.009212,0.008903,0.002369,103.221595,0.021814,0.000671,0.021850,9.978,...,NaN,NaN,NaN,NaN,41305.0,0.997880,0.997874,0.997887,NaN,2025-04-10

In [6]:
rep_FI_names=pd.read_excel('Helper files/'+'Helperfile_Ulu_mounts.xlsx',sheet_name='Sheet1')
Ulu_reps = pd.merge(Ulu, rep_FI_names, on=['filename', 'date_object','sec since midnight'])
Ulu_reps = Ulu_reps[~Ulu_reps['filename'].str.contains('46m')]
Ulu_reps

,filename,Density g/cm3,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),σ Density g/cm3 (from densimeter),Corrected_Splitting,Corrected_Splitting_σ,Corrected_Splitting_σ_Ne,Corrected_Splitting_σ_peak_fit,power (mW),...,pixels wide,pixels high,mag,real image width(um),decrepit,melt film,spinel,sulfide,shape,Comment
0,FG04-A1-4_end-rep4,0.691120,0.002862,0.001573,0.002391,104.328535,0.003087,0.000529,0.003048,5.994,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FG04-A1-4_end-rep5,0.701827,0.002909,0.001653,0.002394,104.349488,0.003226,0.000531,0.003189,5.996,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FG04-A1-4_end-rep6,0.694049,0.002787,0.001431,0.002392,104.334278,0.002803,0.000533,0.002758,6.010,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FG04-A1-4_start-rep1,0.690485,0.004501,0.003814,0.002391,104.327289,0.007486,0.000517,0.007484,5.987,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FG04-A1-4_start-rep2,0.693988,0.004277,0.003546,0.002392,104.334157,0.006949,0.000515,0.006944,5.950,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,KL0930_c312_a1_FIA,0.194130,0.002636,0.001158,0.002368,103.228909,0.002836,0.000663,0.002763,5.990,...,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,Ellipsoid,has melt. large
223,KL0930_c312_a2_FIB,0.153764,0.006101,0.004682,0.003912,103.138312,0.011816,0.000661,0.011822,5.994,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ellipsoid,NaN
224,KL0930_c318_a1_FIA,0.119719,0.003993,0.001138,0.003827,103.052394,0.002872,0.000666,0.002800,10.008,...,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,Capsule (short),NaN
225,KL0930_c321_a1_FIA,0.165620,0.007694,0.006600,0.003954,103.168233,0.016657,0.000672,0.016679,9.985,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Capsule (short),NaN
226,KL0930_c321_a2_FIB,0.191143,0.009212,0.008903,0.002369,103.221595,0.021814,0.000671,0.021850,9.978,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ellipsoid,NaN

## Now let's take mean of repeated analyses

In [7]:
grouped = Ulu_reps.groupby('FI_name')

# Separate numeric and non-numeric columns
numeric_cols = Ulu_reps.select_dtypes(include='number')
non_numeric_cols = Ulu_reps.select_dtypes(exclude='number')

# Aggregate numeric columns by mean and standard deviation
numeric_Ulu_averaged_mean = grouped[numeric_cols.columns].mean()
numeric_Ulu_averaged_std = grouped[numeric_cols.columns].std()

# Take the first instance for non-numeric columns
non_numeric_Ulu_averaged = grouped[non_numeric_cols.columns].first()

# Concatenate Ulu_averageds and reindex columns to the original order
Ulu_averaged = pd.concat([numeric_Ulu_averaged_mean, non_numeric_Ulu_averaged], axis=1)
Ulu_averaged = Ulu_averaged.reindex(columns=Ulu_reps.columns)

# Add standard deviation columns after reindexing
Ulu_averaged = pd.concat([Ulu_averaged, numeric_Ulu_averaged_std.add_suffix('_Raman_STD')], axis=1)

# Reset index to get a DataFrame
Ulu_averaged = Ulu_averaged.reset_index(drop=True)

row_counts = grouped.size().reset_index(name='row_count')

# Add a new column "averaged?" based on the row count
row_counts['averaged?'] = 'No'
row_counts.loc[row_counts['row_count'] > 1, 'averaged?'] = 'Yes'

# Merge the row counts back to the aggregated DataFrame
Ulu_averaged = pd.merge(Ulu_averaged, row_counts[['FI_name', 'averaged?']], on='FI_name', how='left')

# If there are missing values (groups with a single row), fill them with 'No'
Ulu_averaged['averaged?'] = Ulu_averaged['averaged?'].fillna('No')

#exclude a weird null average spectrum
# Ulu_averaged=Ulu_averaged[~(Ulu_averaged['filename'].str.contains("186-9-118-A"))]
Ulu_averaged.to_excel(compilation_folder+'/'+"Ulu_Raman_averaged.xlsx")

Ulu_averaged

,filename,Density g/cm3,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),σ Density g/cm3 (from densimeter),Corrected_Splitting,Corrected_Splitting_σ,Corrected_Splitting_σ_Ne,Corrected_Splitting_σ_peak_fit,power (mW),...,Unnamed: 20_Raman_STD,Area_Raman_STD,FI_axis_a_um_Raman_STD,FI_axis_b_um_Raman_STD,Angle_Raman_STD,pixels wide_Raman_STD,pixels high_Raman_STD,mag_Raman_STD,real image width(um)_Raman_STD,averaged?
0,FG04-A1-1-evening_r2,0.598161,0.002916,0.001698,0.002370,104.141808,0.003491,0.000728,0.003422,6.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
1,FG04-A1-1-50X-evening-r2,0.622736,0.003053,0.001919,0.002375,104.192018,0.003896,0.000608,0.003857,5.998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
2,FG04-A1-1_eve_r2_100X,0.647180,0.004943,0.004333,0.002380,104.241355,0.008691,0.000858,0.008667,6.041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
3,FG04-A1-1-100X-eve-r2,0.622901,0.005599,0.005070,0.002375,104.192354,0.010295,0.000737,0.010291,6.017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
4,FG04-A1-1-100X-eve-r2,0.598815,0.006060,0.005577,0.002370,104.143151,0.011461,0.000612,0.011469,6.019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,KL0931_c034_a1_FIH,0.108702,0.010465,0.009746,0.003812,103.024588,0.024596,0.000566,0.024641,10.076,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
200,KL0931_c159_a1_FIA,0.077921,0.010195,0.009458,0.003803,102.946907,0.023870,0.000692,0.023912,9.931,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
201,KL0931_c160_a1_FIA,0.150407,0.009614,0.008787,0.003901,103.129840,0.022175,0.000695,0.022212,9.976,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
202,KL0931_c240_a1_FIA,0.107876,0.005193,0.003527,0.003812,103.022505,0.008902,0.000829,0.008883,10.029,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
203,KL0931_c240_a1_FIB,0.090379,0.009066,0.008230,0.003801,102.978346,0.020771,0.000831,0.020799,10.015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No