# Merging new data with Literature and simplifying dataset for plotting
This notebook compiles the data from this study, with Lerner (2024, EPSL), Devitre (2024, GPL) and Devitre (2024,JPET)
- 1. Import dependencies and install packages
- 2. Import datasets
- 3. Merge and simplify into a combined dataframe for plotting

## 1. Import packages and setup folders and paths

### Import packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import os

mpl.rcParams['pdf.fonttype'] = 42  # 42 is for TrueType fonts
mpl.rcParams['font.size'] = 7
mpl.rcParams["font.family"] = "serif"
mpl.rcParams["font.serif"] = ["Times New Roman"]

### Setup folders and data paths

In [2]:
# This is to make sure the code runs regardless of operating system
if os.name=='posix':
    slash='/'
else:
    slash='\\'

# Set master folder
MasterFolder=os.path.dirname(os.getcwd())

#Folder to save figures

figpath=MasterFolder +slash+"Plotting_notebooks"+slash+'Notebook_Figs'
if not os.path.exists(figpath):
    os.mkdir(figpath)
# Create folder to save full datasets

compilation_folder=MasterFolder +slash+"Plotting_notebooks"+slash+'Notebook_Compiled_data'
if not os.path.exists(compilation_folder):
    os.mkdir(compilation_folder)

## 2. Import all datasets


### Import new data from this study

In [6]:
newdata_og=pd.read_excel(MasterFolder +slash+"Data_processing_notebooks"+slash+'Notebook_Compiled_data'+slash+'FinalNewDataset.xlsx')

newdata_og =newdata_og.loc[:, ~newdata_og.columns.str.contains('Unnamed')].copy()
newdata_og = newdata_og.drop(columns='i')
newdata_og['Day']=newdata_og['Day'].astype(int)
newdata_og.insert(newdata_og.columns.get_loc('Atomic %_Ti_Ol')+1,'Total_Atomic%_Ol',newdata_og.loc[:, (newdata_og.columns.str.contains('Atomic'))&(newdata_og.columns.str.contains('Ol'))].sum(axis=1).where(lambda x: x != 0, np.nan))
newdata_og.insert(newdata_og.columns.get_loc('Total_Atomic%_Ol')+1,'(Mg+Fe)/Si_Atomic%_Ol',(newdata_og['Atomic %_Mg_Ol']+newdata_og['Atomic %_Fe_Ol'])/newdata_og['Atomic %_Si_Ol'].where(lambda x: x != 0, np.nan))
newdata_og.insert(newdata_og.columns.get_loc('σ Density g/cm3 (from densimeter)'),'σ Density g/cm3 (from DiadFit for individual, Std dev for averaged FI)',np.nan)

newdata_og

,filename,Density g/cm3,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),"σ Density g/cm3 (from DiadFit for individual, Std dev for averaged FI)",σ Density g/cm3 (from densimeter),Corrected_Splitting,Corrected_Splitting_σ,Corrected_Splitting_σ_Ne,Corrected_Splitting_σ_peak_fit,...,T_K_input,error_T_K,CO2_dens_gcm3_input,error_CO2_dens_gcm3,crust_dens_kgm3_input,error_crust_dens_kgm3,model,EOS,XH2O_input,error_XH2O
0,919_50_FIA,0.141984,0.008781,0.007880,NaN,0.003876,103.108584,0.019886,0.000992,0.019891,...,1586.067191,50,0.141984,0.008781,NaN,0,denlinger_lerner,DZ06,0.065145,0.033490
1,919_50_FIB,0.151694,0.004892,0.002947,NaN,0.003905,103.133089,0.007437,0.000995,0.007381,...,1586.067191,50,0.151694,0.004892,NaN,0,denlinger_lerner,DZ06,0.061202,0.031835
2,919_51_FIA,0.191270,0.004434,0.003749,NaN,0.002369,103.221905,0.009185,0.001005,0.009143,...,1585.870579,50,0.191270,0.004434,NaN,0,denlinger_lerner,DZ06,0.051709,0.028335
3,919_52_FIA,0.153743,0.004916,0.002978,NaN,0.003912,103.138260,0.007515,0.001008,0.007458,...,1581.879866,50,0.153743,0.004916,NaN,0,denlinger_lerner,DZ06,0.060602,0.031591
4,919_52_FIB,0.143131,0.005096,0.003305,NaN,0.003879,103.111478,0.008341,0.001011,0.008292,...,1582.911649,50,0.143131,0.005096,NaN,0,denlinger_lerner,DZ06,0.064755,0.033323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,UW7-OX6-FI#2-12mW-R1,0.134985,0.003937,0.000779,NaN,0.003858,103.090919,0.001967,0.000614,0.001871,...,1578.825924,50,0.134985,0.002217,NaN,0,denlinger_lerner,DZ06,0.068803,0.035080
528,UW7-OX7-FI#1,0.171994,0.003587,0.002689,NaN,0.002373,103.174533,0.006629,0.000615,0.006614,...,1516.338771,50,0.171994,0.003587,NaN,0,denlinger_lerner,DZ06,0.057018,0.030187
529,UW7-OX8-FI#1,0.120475,0.003967,0.001040,NaN,0.003829,103.054301,0.002625,0.000615,0.002557,...,1481.912994,50,0.120475,0.003967,NaN,0,denlinger_lerner,DZ06,0.082338,0.041236
530,UW7-OX8-FI#2,0.126914,0.004174,0.001635,NaN,0.003840,103.070551,0.004127,0.000616,0.004090,...,1481.912994,50,0.126914,0.004174,NaN,0,denlinger_lerner,DZ06,0.078040,0.039251
531,UW7-OX9-FI#1,0.143185,0.003972,0.000852,NaN,0.003880,103.111614,0.002150,0.000617,0.002064,...,1608.330671,50,0.143185,0.003972,NaN,0,denlinger_lerner,DZ06,0.063815,0.032931

### Import the re-processed JPET data (September 2023 rapid response)
We re-processed (SO2 mol%, T from Fo, XH2O and PD MC simulations) this literature dataset for consistency in comparisons

In [7]:
K23=pd.read_excel(MasterFolder +slash+"Data_processing_notebooks"+slash+'Data_reprocessing_Literature'+slash+'Notebook_Compiled_data'+slash+'K23_recalculated.xlsx')

## We need to drop some old columns and rename some others to merge correctly with the new data

K23 =K23.loc[:, ~K23.columns.str.contains('Unnamed|Old|P_kbar_1150C|SO2_mol%|py_index|Recalculations for Pre-Post Caldera paper >|T_C')]
K23 = K23.drop(columns='i')
K23['decrepit']=K23['decrepit'].astype(object)
K23['sulfide']=K23['sulfide'].astype(object)
K23.drop(columns=['Column headers', 'EDS Data >>', 'Depth (km)_ryanlerner',], inplace=True)
K23.rename(columns={'Corrected_Splitting (cm-1)':'Corrected_Splitting', 
                     'Splitting (cm-1)':'Splitting',
                    'Crystal Name':'Sample_crystal',
                    'EDS_Name':'Name_on_SEM',
                    'FI Name':'FI_name',
                    'O':'Atomic %_O_Ol','Mg':'Atomic %_Mg_Ol','Fe':'Atomic %_Fe_Ol','Si':'Atomic %_Si_Ol',
                    'Total':"Total_Atomic%_Ol",
                    '(Mg+Fe)/Si':'(Mg+Fe)/Si_Atomic%_Ol',
                    'Filename':'filename',
                    'Fo':'Fo_Ol',
                    'SO2 mol%_recalculated':'SO2 mol%',
                    'σ Density g/cm3 (DiadFit)':'σ Density g/cm3',
                    'Reported density mean of reps?':'averaged?',
                    'STDofreps_Density g/cm3':'Density g/cm3_Raman_STD',
                    'σ Density g/cm3 (as plotted, from DiadFit for individual, Std dev for averaged FI)':'σ Density g/cm3 (from DiadFit for individual, Std dev for averaged FI)'}
                    , inplace=True)

K23

,Sample_crystal,FI_name,averaged?,Density g/cm3,"σ Density g/cm3 (from DiadFit for individual, Std dev for averaged FI)",Density g/cm3_Raman_STD,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),σ Density g/cm3 (from densimeter),Corrected_Splitting,...,T_K_input,error_T_K,CO2_dens_gcm3_input,error_CO2_dens_gcm3,crust_dens_kgm3_input,error_crust_dens_kgm3,model,EOS,XH2O_input,error_XH2O
0,K23_101,K23_101_FIC,No,0.085665,0.007736,NaN,0.007736,0.006738,0.003801,102.966450,...,1565.805593,50,0.085665,0.007736,NaN,0,denlinger_lerner,DZ06,0.108233,0.053578
1,K23_101,K23_101_FID,No,0.100137,0.005037,NaN,0.005037,0.003301,0.003805,103.002974,...,1565.805593,50,0.100137,0.005037,NaN,0,denlinger_lerner,DZ06,0.093852,0.046643
2,K23_102,K23_102_FIA,No,0.112454,0.004482,NaN,0.004482,0.002350,0.003817,103.034058,...,1564.096549,50,0.112454,0.004482,NaN,0,denlinger_lerner,DZ06,0.083756,0.041885
3,KS23_103,K23_103_FIC,No,0.114374,0.004013,NaN,0.004013,0.001231,0.003819,103.038904,...,1511.482018,50,0.114374,0.004013,NaN,0,denlinger_lerner,DZ06,0.085135,0.042535
4,KS23_103,K23_103_FID,Yes,0.126346,0.001619,0.001619,0.004087,0.001400,0.003839,103.069118,...,1511.482018,50,0.126346,0.001619,NaN,0,denlinger_lerner,DZ06,0.076872,0.038712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,K23_7,K23_7_FIA,No,0.118112,0.003895,NaN,0.003895,0.000734,0.003825,103.048338,...,1457.137953,50,0.118112,0.003895,NaN,0,denlinger_lerner,DZ06,0.085425,0.042681
58,K23_7,K23_7_FIB,No,0.115662,0.004004,NaN,0.004004,0.001198,0.003821,103.042155,...,1457.137953,50,0.115662,0.004004,NaN,0,denlinger_lerner,DZ06,0.087248,0.043536
59,K23_7,K23_7_FIC,No,0.112891,0.004063,NaN,0.004063,0.001390,0.003817,103.035161,...,1457.137953,50,0.112891,0.004063,NaN,0,denlinger_lerner,DZ06,0.089382,0.044542
60,K23_9,K23_9_FIA,No,0.083276,0.004746,NaN,0.004746,0.002841,0.003801,102.960422,...,1504.386368,50,0.083276,0.004746,NaN,0,denlinger_lerner,DZ06,0.114549,0.056688
61,KS23_9,K23_9_FIA,No,0.114913,0.023538,NaN,0.023538,0.023226,0.003820,103.040265,...,1504.386368,50,0.114913,0.023538,NaN,0,denlinger_lerner,DZ06,0.085122,0.042531

### Merge K23 with the new data and add sample eruption origin + event description
- the location column is to identify the region of the eruption (SSWRZ, VSWRZ, ERZ, Summit)

In [8]:
## Merge the data
newdata=pd.merge(newdata_og,K23,how='outer')
## fill nan SO2 mol% with 0 and move columns for visualization
newdata['SO2 mol%']=newdata['SO2 mol%'].fillna(0)
cols_to_move = ['Sample', 'Sample_crystal', 'FI_name','averaged?']
other_cols = [c for c in newdata.columns if c not in cols_to_move]
newdata = newdata[cols_to_move + other_cols]

## Make sure FI_type column is str
newdata['FI_type']=newdata['FI_type'].astype(str)

## Add eruption location column
newdata=newdata.copy()
newdata['Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)']= ''

newdata.loc[newdata['Sample'].str.contains('914|916|917|924|K20|K23|KD24'),'Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)'] = "Summit"
newdata.loc[newdata['Sample'].str.contains('UW'),'Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)'] = "Explosive Era"
newdata.loc[newdata['Sample'].str.contains('L84|909|908|910'),'Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)'] = "ERZ"
newdata.loc[newdata['Sample'].str.contains('919|920|K24|K21|921'),'Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)'] = "SSWRZ"
newdata.loc[newdata['Sample'].str.contains('930|931'),'Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)'] = "VSWRZ"

## Add Event description
newdata['Eruption_title']= ''

eruption_map = {
    r"UW": "Kulanaokuaiki \n(400-650)",
    r"K21|921": "Circ. flow\n(~1700)",
    r"L84": "Sand Hill\n(1840)",
    r"930": "Mauna Iki VSWRZ\n(1919-1920)",
    r"909": "ERZ (May 1969)",
    r"908": "ERZ (Dec 1969)",
    r"916": "IC (Aug 1971)",
    r"931": "VSWRZ\n(Sep 1971)",
    r"914": "IC\n(Sep 1971)",
    r"910": "ERZ (Nov 1973)",
    r"917": "IC\n(Jul 1974)",
    r"924": "EC\n (Jul 1974)",
    r"919|920": "SSWRZ\n(Dec 1974)",
    r"K20": "IC\n(Dec 2020)",
    r"K23": "IC\n(Sept 2023)",
    r"K24": "SSWRZ\n(June 2024)",
    r"KD24": "IC\n(Dec 2024)"
}

for pattern, title in eruption_map.items():
    newdata.loc[newdata['Sample'].str.contains(pattern, regex=True), 'Eruption_title'] = title

newdata.head()

,Sample,Sample_crystal,FI_name,averaged?,filename,Density g/cm3,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),"σ Density g/cm3 (from DiadFit for individual, Std dev for averaged FI)",σ Density g/cm3 (from densimeter),...,CO2_dens_gcm3_input,error_CO2_dens_gcm3,crust_dens_kgm3_input,error_crust_dens_kgm3,model,EOS,XH2O_input,error_XH2O,"Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)",Eruption_title
0,K23,K23_2,K23_2_FIA,No,NaN,0.004106,0.000000,0.000000,0.0,0.000000,...,0.004106,0.000000,NaN,0,denlinger_lerner,DZ06,0.263381,0.145350,Summit,IC\n(Sept 2023)
1,KL0920,KL0920_c216,KL0920_c216_a2_FID,No,KL0920_c216_a2_FID,0.006448,0.020385,0.019995,NaN,0.003967,...,0.006448,0.020385,NaN,0,denlinger_lerner,DZ06,0.257385,0.140755,SSWRZ,SSWRZ\n(Dec 1974)
2,K24,K24_5,K24_5_FIA,No,K24_5_FIA,0.008291,0.005223,0.003406,NaN,0.003960,...,0.008291,0.005223,NaN,0,denlinger_lerner,DZ06,0.250687,0.135796,SSWRZ,SSWRZ\n(June 2024)
3,KL0921,KL0921_c288,KL0921_c288_a1_FIA,No,KL0921_c288_a1_FIA,0.009482,0.015142,0.014616,NaN,0.003955,...,0.009482,0.015142,NaN,0,denlinger_lerner,DZ06,0.248156,0.133970,SSWRZ,Circ. flow\n(~1700)
4,K21,K21_78b,K21_78b_FI#5,No,K21-78b-FI#5,0.009713,0.009637,0.008789,NaN,0.003954,...,0.009713,0.009637,NaN,0,denlinger_lerner,DZ06,0.246373,0.132693,SSWRZ,Circ. flow\n(~1700)

### Import the re-processed LERZ 2018 data (GPL paper)
- We re-processed (SO2 mol%, T from Fo, XH2O and PD MC simulations) this literature dataset for consistency in comparisons
- I can't merge the whole LERZ dataframe, it's too different, I'd have to rename 224 columns
- Considering this, we can create a simplified dataframe with only the essentials.
- This does require cleaning up some of the essential columns

In [9]:
LERZ2018=pd.read_excel(MasterFolder +slash+"Data_processing_notebooks"+slash+'Data_reprocessing_Literature'+slash+'Notebook_Compiled_data'+slash+'LERZ2018_recalculated.xlsx')
LERZ2018 =LERZ2018.loc[:, ~LERZ2018.columns.str.contains('Unnamed')]
LERZ2018['Day']=LERZ2018['Day'].astype(int)
LERZ2018['Int_time (s)']=LERZ2018['Int_time (s)'].astype(float)
LERZ2018=LERZ2018.copy()
LERZ2018['Sample_crystal']=LERZ2018['Host crystal ID']
LERZ2018['SO2 mol%']=LERZ2018['SO2 mol%_recalculated'].fillna(0)
LERZ2018['Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)']= 'ERZ'
LERZ2018['Eruption_title']= 'LERZ\n(May-Aug 2018)'
LERZ2018['Sample']=LERZ2018["Event ID (LL8 - July, LL7-Aug, LL4-May)"]
LERZ2018['FI_name']=LERZ2018['Fluid inclusion ID']
LERZ2018.rename(columns={'FeO_Gl':'FeOt_Gl',
                         'FeO_STD_Gl':'FeOt_STD_Gl',
                         'FI_axis_a_um':'FI_axis_a_pixels',
                         'FI_axis_b_um':'FI_axis_b_pixels'} 
                     , inplace=True)

display(LERZ2018.head())
only_in_LERZ2018 = set(LERZ2018.columns) - set(newdata.columns)
print("Columns only in LERZ 2018: "+ str(len(only_in_LERZ2018)))

,Py_index,Event Description,"Event ID (LL8 - July, LL7-Aug, LL4-May)",Host crystal ID,Fluid inclusion ID,Raman Data >,Fermi Diad separation ΔCO2 (cm-1),Corrected ΔCO2 (cm-1),Corrected ΔCO2 1σ (cm-1),CO2 density (g/cm3),...,H2O (wt%)_STD_Gl,averaged?_Gl,#of analyses (when averaged)_Gl,non_numeric_column_behavior_used (First/Last instance kept or skipped)_Gl,Sample_crystal,SO2 mol%,"Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)",Eruption_title,Sample,FI_name
0,0,"LERZ, Fissure 8, May 30th 2018",LL4,LL4-14dp,LL4-14dp-FI#1,ν1 refers to the low wavenumber band of the fe...,103.416763,103.186144,0.006461,0.176605,...,0.011157,Yes,19,skip,LL4-14dp,4.088172,ERZ,LERZ\n(May-Aug 2018),LL4,LL4-14dp-FI#1
1,1,"LERZ, Fissure 8, May 30th 2018",LL4,LL4-14dp,LL4-14dp-FI#2,NaN,103.431244,103.195894,0.007137,0.180578,...,0.011157,Yes,19,skip,LL4-14dp,2.406601,ERZ,LERZ\n(May-Aug 2018),LL4,LL4-14dp-FI#2
2,2,"LERZ, Fissure 8, May 30th 2018",LL4,LL4-14dp,LL4-14dp-MI#1,NaN,103.429713,103.196578,0.010404,0.180858,...,0.011157,Yes,19,skip,LL4-14dp,6.492751,ERZ,LERZ\n(May-Aug 2018),LL4,LL4-14dp-MI#1
3,3,"LERZ, Fissure 8, May 30th 2018",LL4,LL4-21,LL4-21-#2,NaN,103.379425,103.122405,0.001766,0.147317,...,0.011157,Yes,19,skip,LL4-21,0.000000,ERZ,LERZ\n(May-Aug 2018),LL4,LL4-21-#2
4,7,"LERZ, Fissure 8, May 30th 2018",LL4,LL4-21,LL4-21-MI#5,NaN,103.170121,102.953345,0.007431,0.080378,...,0.011157,Yes,19,skip,LL4-21,0.000000,ERZ,LERZ\n(May-Aug 2018),LL4,LL4-21-MI#5

Columns only in LERZ 2018: 224

### Import reprocessed Lerner 2024 (EPSL) data for Keanakakoi
- Same thing, we have to clean it up and extract essentials, as it's very different

In [10]:
Lerner=pd.read_excel(MasterFolder +slash+"Data_processing_notebooks"+slash+'Data_reprocessing_Literature'+slash+'Notebook_Compiled_data'+slash+'Lerner2025_recalculated.xlsx')
Lerner =Lerner.loc[:, ~Lerner.columns.str.contains('Unnamed')]
Lerner=Lerner.copy()
Lerner[['Sample_code', 'crystalFI']] = Lerner['Sample Name\n(melt inclusions and fluid inclusions)'].str.split('_', n=1, expand=True)
Lerner[['crystal_num', 'crystal_suffix']] = Lerner['crystalFI'].str.extract(r'^(\d+)([A-Za-z]+)?$')
Lerner['Sample_crystal']=Lerner['Sample_code']+"_"+Lerner['crystal_num']
Lerner['Eruption_title']="Early Keanakākoʻi\n(1500-1650 CE)"
Lerner['Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)']="Explosive Era"
Lerner['FI_name']=Lerner['Sample Name\n(melt inclusions and fluid inclusions)']
Lerner['FI_type']=np.where(Lerner['Inclusion notes'].str.contains("Isolated|isolated"),'P',np.nan)
Lerner['SO2 mol%']=np.nan
Lerner['Sample']=Lerner['Sample_code']

Lerner.rename(columns={'FeOT_Gl':'FeOt_Gl',
                       'FeOT_STD_Gl':'FeOt_STD_Gl'
                         } 
                     , inplace=True)

Lerner.head()
Lerner[Lerner['Fluid inclusion notes'].str.contains("Two-phase")] ## These were calculated weird

,Sample_ID,Sample Name\n(melt inclusions and fluid inclusions),Keanakākoʻi Tephra unit name\n(Swanson & Houghton 2018 nomenclature),Sample,Keanakākoʻi Tephra unit description,Eruption Date (CE),Sample Site: Latitude (WGS84),Sample Site: Longitude (WGS84),Inclusion type,Inclusion notes,...,Sample_code,crystalFI,crystal_num,crystal_suffix,Sample_crystal,Eruption_title,"Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)",FI_name,FI_type,SO2 mol%
16,SW3,SW3_10b,"D, lower",SW3,vitric ash 2A1,1500-1650,19.38981,-155.29229,fluid inclusion,Isolated fluid inclusion,...,SW3,10b,10,b,SW3_10,Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,SW3_10b,P,NaN
17,SW3,SW3_10c,"D, lower",SW3,vitric ash 2A1,1500-1650,19.38981,-155.29229,fluid inclusion,Isolated fluid inclusion,...,SW3,10c,10,c,SW3_10,Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,SW3_10c,P,NaN
18,SW3,SW3_10d,"D, lower",SW3,vitric ash 2A1,1500-1650,19.38981,-155.29229,fluid inclusion,Isolated fluid inclusion,...,SW3,10d,10,d,SW3_10,Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,SW3_10d,P,NaN
19,SW3,SW3_10e,"D, lower",SW3,vitric ash 2A1,1500-1650,19.38981,-155.29229,fluid inclusion,Isolated fluid inclusion,...,SW3,10e,10,e,SW3_10,Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,SW3_10e,P,NaN
20,SW3,SW3_16a,"D, lower",SW3,vitric ash 2A1,1500-1650,19.38981,-155.29229,fluid inclusion,Isolated fluid inclusion,...,SW3,16a,16,a,SW3_16,Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,SW3_16a,P,NaN
21,SW3,SW3_16b,"D, lower",SW3,vitric ash 2A1,1500-1650,19.38981,-155.29229,fluid inclusion,Isolated fluid inclusion,...,SW3,16b,16,b,SW3_16,Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,SW3_16b,P,NaN
30,K99-5,K99-5_5a,"D, upper",K99-5,vitric ash 2A2,1500-1650,19.38981,-155.29229,fluid inclusion,Isolated fluid inclusion,...,K99-5,5a,5,a,K99-5_5,Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,K99-5_5a,P,NaN
31,K99-5,K99-5_5b,"D, upper",K99-5,vitric ash 2A2,1500-1650,19.38981,-155.29229,fluid inclusion,Isolated fluid inclusion,...,K99-5,5b,5,b,K99-5_5,Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,K99-5_5b,P,NaN
32,K99-5,K99-5_5c,"D, upper",K99-5,vitric ash 2A2,1500-1650,19.38981,-155.29229,fluid inclusion,Isolated fluid inclusion,...,K99-5,5c,5,c,K99-5_5,Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,K99-5_5c,P,NaN
33,K99-5,K99-5_5d,"D, upper",K99-5,vitric ash 2A2,1500-1650,19.38981,-155.29229,fluid inclusion,Isolated fluid inclusion,...,K99-5,5d,5,d,K99-5_5,Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,K99-5_5d,P,NaN
34,K99-5,K99-5_5e,"D, upper",K99-5,vitric ash 2A2,1500-1650,19.38981,-155.29229,fluid inclusion,Isolated fluid inclusion,...,K99-5,5e,5,e,K99-5_5,Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,K99-5_5e,P,NaN
35,K99-5,K99-5_5f,"D, upper",K99-5,vitric ash 2A2,1500-1650,19.38981,-155.29229,fluid inclusion,Isolated fluid inclusion,...,K99-5,5f,5,f,K99-5_5,Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,K99-5_5f,P,NaN

## 3. Export full frames and merge into a single simplified dataframe 
- We clean up the datasets a bit (name consistency etc)
- We calculate FI sizes (radii, areas, volumes)
- We add coordinates to the data 
- We merge all of it into a single, albeit simplified, dataframe used for plotting. All other data is stored on the github repo.

### First, clean up the datasets and add some missing things

#### Let's add sample coordinates for our data
- This is taken from the Hawaii map folder, it is a set of coordinates used to make the map.

In [11]:
#Load sample coordinates to paste in dataframe
sample_coordinates = pd.read_csv(MasterFolder+slash+"Paper"+slash+"Map Hawaii"+slash+"Eruptions_Kilauea_coordinates.csv")

# Merge them on the newdata frame
newdata=pd.merge(left=newdata,right=sample_coordinates,on='Sample',how='left')
newdata=newdata.copy()

# Merge on LERZ2018
LERZ2018=pd.merge(left=LERZ2018,right=sample_coordinates,on='Sample',how='left')
LERZ2018=LERZ2018.copy()

display(newdata.head())
display(LERZ2018.head())

,Sample,Sample_crystal,FI_name,averaged?,filename,Density g/cm3,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),"σ Density g/cm3 (from DiadFit for individual, Std dev for averaged FI)",σ Density g/cm3 (from densimeter),...,crust_dens_kgm3_input,error_crust_dens_kgm3,model,EOS,XH2O_input,error_XH2O,"Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)",Eruption_title,Sample Site: Longitude (WGS84),Sample Site: Latitude (WGS84)
0,K23,K23_2,K23_2_FIA,No,NaN,0.004106,0.000000,0.000000,0.0,0.000000,...,NaN,0,denlinger_lerner,DZ06,0.263381,0.145350,Summit,IC\n(Sept 2023),-155.267850,19.407830
1,KL0920,KL0920_c216,KL0920_c216_a2_FID,No,KL0920_c216_a2_FID,0.006448,0.020385,0.019995,NaN,0.003967,...,NaN,0,denlinger_lerner,DZ06,0.257385,0.140755,SSWRZ,SSWRZ\n(Dec 1974),-155.295217,19.380050
2,K24,K24_5,K24_5_FIA,No,K24_5_FIA,0.008291,0.005223,0.003406,NaN,0.003960,...,NaN,0,denlinger_lerner,DZ06,0.250687,0.135796,SSWRZ,SSWRZ\n(June 2024),-155.298120,19.375625
3,KL0921,KL0921_c288,KL0921_c288_a1_FIA,No,KL0921_c288_a1_FIA,0.009482,0.015142,0.014616,NaN,0.003955,...,NaN,0,denlinger_lerner,DZ06,0.248156,0.133970,SSWRZ,Circ. flow\n(~1700),-155.291070,19.383150
4,K21,K21_78b,K21_78b_FI#5,No,K21-78b-FI#5,0.009713,0.009637,0.008789,NaN,0.003954,...,NaN,0,denlinger_lerner,DZ06,0.246373,0.132693,SSWRZ,Circ. flow\n(~1700),-155.291070,19.383150

,Py_index,Event Description,"Event ID (LL8 - July, LL7-Aug, LL4-May)",Host crystal ID,Fluid inclusion ID,Raman Data >,Fermi Diad separation ΔCO2 (cm-1),Corrected ΔCO2 (cm-1),Corrected ΔCO2 1σ (cm-1),CO2 density (g/cm3),...,#of analyses (when averaged)_Gl,non_numeric_column_behavior_used (First/Last instance kept or skipped)_Gl,Sample_crystal,SO2 mol%,"Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)",Eruption_title,Sample,FI_name,Sample Site: Longitude (WGS84),Sample Site: Latitude (WGS84)
0,0,"LERZ, Fissure 8, May 30th 2018",LL4,LL4-14dp,LL4-14dp-FI#1,ν1 refers to the low wavenumber band of the fe...,103.416763,103.186144,0.006461,0.176605,...,19,skip,LL4-14dp,4.088172,ERZ,LERZ\n(May-Aug 2018),LL4,LL4-14dp-FI#1,-154.91439,19.462477
1,1,"LERZ, Fissure 8, May 30th 2018",LL4,LL4-14dp,LL4-14dp-FI#2,NaN,103.431244,103.195894,0.007137,0.180578,...,19,skip,LL4-14dp,2.406601,ERZ,LERZ\n(May-Aug 2018),LL4,LL4-14dp-FI#2,-154.91439,19.462477
2,2,"LERZ, Fissure 8, May 30th 2018",LL4,LL4-14dp,LL4-14dp-MI#1,NaN,103.429713,103.196578,0.010404,0.180858,...,19,skip,LL4-14dp,6.492751,ERZ,LERZ\n(May-Aug 2018),LL4,LL4-14dp-MI#1,-154.91439,19.462477
3,3,"LERZ, Fissure 8, May 30th 2018",LL4,LL4-21,LL4-21-#2,NaN,103.379425,103.122405,0.001766,0.147317,...,19,skip,LL4-21,0.000000,ERZ,LERZ\n(May-Aug 2018),LL4,LL4-21-#2,-154.91439,19.462477
4,7,"LERZ, Fissure 8, May 30th 2018",LL4,LL4-21,LL4-21-MI#5,NaN,103.170121,102.953345,0.007431,0.080378,...,19,skip,LL4-21,0.000000,ERZ,LERZ\n(May-Aug 2018),LL4,LL4-21-MI#5,-154.91439,19.462477

#### Now let's clean up the three frames a bit
- We rename important columns to match, add missing ones, and calculate some where relevant

In [12]:
### Clean up the dataframes a bit to ease merging into the subframe

Lerner['Fo_Ol_%']=Lerner['Fo host (olivine Mg#)']
LERZ2018['Fo_Ol_%']=LERZ2018['Corrected Fo content (molar %)_Cambridge']
newdata['Fo_Ol_%']=newdata['Fo_Ol']*100

cols_to_add_2LernerLERZ2018 = [
    'EBSDname+grainID_EBSDdata',
    'GOS',
    'Grain Size (pixels)',
    'Grain Size (um2)',
    'subBoundaryLength (um)',
    'equivalentRadius (um)',
    'GB Length/Sqrt Size',
    'Total GB length'
]
cols_to_add_2Lerner = [
    'decrepit',
    'power (mW)',
    'Spectral Center',
    'Mag (X)'
]

cols_to_add_2UCB=['Keanakākoʻi Tephra unit name\n(Swanson & Houghton 2018 nomenclature)',
 'Keanakākoʻi Tephra unit description',
 'Eruption Date (CE)']

LERZ2018[cols_to_add_2LernerLERZ2018+cols_to_add_2UCB] = np.nan
Lerner[cols_to_add_2LernerLERZ2018+cols_to_add_2Lerner]=np.nan

LERZ2018['Eruption Date (CE)']=2018
newdata['Eruption Date (CE)']=newdata['Eruption_title'].str.extract(r'\(([^)]*)\)')
newdata['Fluid inclusion notes']=newdata['Comment']
LERZ2018['Fluid inclusion notes']=LERZ2018['Comment']

newdata.rename(columns={ 'FI_axis_a_um':'FI_axis_a_pixels',
                         'FI_axis_b_um':'FI_axis_b_pixels'} 
                     , inplace=True)

newdata['Reference'] = np.where(newdata['Sample'] == 'K23','Devitre et al. (2024, JPET)','this study')
LERZ2018['Reference'] = 'Devitre et al. (2024, GPL)+Wieser et al. (2021, G3)'
Lerner['Reference'] = 'Lerner et al. (2024, EPSL)'

LERZ2018['σ Density g/cm3']=LERZ2018['error_CO2_dens_gcm3']
LERZ2018['Corrected_Splitting']=LERZ2018['Corrected ΔCO2 (cm-1)']
LERZ2018['Corrected_Splitting_σ']=LERZ2018['Corrected ΔCO2 1σ (cm-1)']

Lerner['σ Density g/cm3']=Lerner['error_CO2_dens_gcm3']
Lerner['Corrected_Splitting']=Lerner['CO2 Fermi diad,  ∆ (cm-1) Raman analyses']
Lerner['Corrected_Splitting_σ']=Lerner['± CO2 Fermi diad 1SE uncertainty,  ∆ (cm-1)']

LERZ2018['Mg#_Gl'] = 100*(LERZ2018['MgO_Gl'] / 40.304) / ((LERZ2018['MgO_Gl'] / 40.304) + (LERZ2018['FeOt_Gl'] / 71.844))

LERZ2018['Total_wt%_Gl']=LERZ2018[['Na2O_Gl',
 'Al2O3_Gl',
 'P2O5_Gl',
 'CaO_Gl',
 'K2O_Gl',
 'TiO2_Gl',
 'SiO2_Gl',
 'MgO_Gl',
 'FeOt_Gl',
 'MnO_Gl']].sum(axis=1)

Lerner['Total_wt%_Gl']=Lerner[['Na2O_Gl',
 'Al2O3_Gl',
 'P2O5_Gl',
 'CaO_Gl',
 'K2O_Gl',
 'TiO2_Gl',
 'SiO2_Gl',
 'MgO_Gl',
 'FeOt_Gl',
 'MnO_Gl']].sum(axis=1)

Lerner.head()

,Sample_ID,Sample Name\n(melt inclusions and fluid inclusions),Keanakākoʻi Tephra unit name\n(Swanson & Houghton 2018 nomenclature),Sample,Keanakākoʻi Tephra unit description,Eruption Date (CE),Sample Site: Latitude (WGS84),Sample Site: Longitude (WGS84),Inclusion type,Inclusion notes,...,Total GB length,decrepit,power (mW),Spectral Center,Mag (X),Reference,σ Density g/cm3,Corrected_Splitting,Corrected_Splitting_σ,Total_wt%_Gl
0,K99-6,K99-6_1c,B,K99-6,lower reticulite,1500,19.42567,-155.25163,fluid inclusion,Isolated fluid inclusion,...,NaN,NaN,NaN,NaN,NaN,"Lerner et al. (2024, EPSL)",3.129780e-03,102.929599,8.816282e-03,99.335289
1,K99-6,K99-6_2d,B,K99-6,lower reticulite,1500,19.42567,-155.25163,fluid inclusion,Isolated fluid inclusion,...,NaN,NaN,NaN,NaN,NaN,"Lerner et al. (2024, EPSL)",2.605323e-14,102.97866,7.586520e-14,99.335289
2,K99-6,K99-6_5b,B,K99-6,lower reticulite,1500,19.42567,-155.25163,fluid inclusion,Isolated fluid inclusion,...,NaN,NaN,NaN,NaN,NaN,"Lerner et al. (2024, EPSL)",8.978184e-04,102.948909,2.529066e-03,99.335289
3,K99-6,K99-6_5d,B,K99-6,lower reticulite,1500,19.42567,-155.25163,fluid inclusion,Isolated fluid inclusion,...,NaN,NaN,NaN,NaN,NaN,"Lerner et al. (2024, EPSL)",2.335182e-03,102.913861,6.577978e-03,99.335289
4,K99-6,K99-6_5e,B,K99-6,lower reticulite,1500,19.42567,-155.25163,fluid inclusion,Isolated fluid inclusion,...,NaN,NaN,NaN,NaN,NaN,"Lerner et al. (2024, EPSL)",2.850298e-04,102.924661,8.029008e-04,99.335289

#### Calculate FI geometry
- Calculates radii, areas and volumes of FI

In [13]:
# Calculate scaled semiaxes for FI 
def scale(row, column_name):
    if row['mag'] == 50:
        return (row[column_name]) * 223.161 / 1920
    elif row['mag'] == 20:
        return (row[column_name]) * 546.419 / 1920
    elif row['mag'] == 100:
        return (row[column_name]) * 109.989 / 1920
    else:
        return None
  
def fi_area(a,b):
    return np.pi*a*b

def fi_vol(a,b,c):
    return (4/3)*np.pi*a*b*c

newdata['FI_semiaxis_a_um'] = newdata.apply(scale, axis=1, column_name='FI_axis_a_pixels')
newdata['FI_semiaxis_b_um'] = newdata.apply(scale, axis=1, column_name='FI_axis_b_pixels')

LERZ2018['FI_semiaxis_a_um'] =LERZ2018.apply(scale, axis=1, column_name='FI_axis_a_pixels')
LERZ2018['FI_semiaxis_b_um'] =LERZ2018.apply(scale, axis=1, column_name='FI_axis_b_pixels')

Lerner['FI_semiaxis_a_um']=Lerner['vapor bubble diameter (um)']/2
Lerner['FI_semiaxis_b_um']=Lerner['vapor bubble diameter (um)']/2

newdata['FI_Area_um2'] = fi_area(newdata['FI_semiaxis_a_um'],newdata['FI_semiaxis_b_um'])
LERZ2018['FI_Area_um2'] = fi_area(LERZ2018['FI_semiaxis_a_um'],LERZ2018['FI_semiaxis_b_um'])
Lerner['FI_Area_um2'] = fi_area(Lerner['FI_semiaxis_a_um'],Lerner['FI_semiaxis_b_um'])

newdata['FI_Volume_um3'] = fi_vol(newdata['FI_semiaxis_a_um'],newdata['FI_semiaxis_b_um'],
                                  (newdata['FI_semiaxis_a_um'] + newdata['FI_semiaxis_b_um'])/2)
LERZ2018['FI_Volume_um3'] = fi_vol(LERZ2018['FI_semiaxis_a_um'],LERZ2018['FI_semiaxis_b_um'],
                                   (LERZ2018['FI_semiaxis_a_um'] + LERZ2018['FI_semiaxis_b_um'])/2)
Lerner['FI_Volume_um3'] = fi_vol(Lerner['FI_semiaxis_a_um'],Lerner['FI_semiaxis_b_um'],
                                 (Lerner['FI_semiaxis_a_um'] + Lerner['FI_semiaxis_b_um'])/2)

### Re-export all three dataframes for safekeeping

In [14]:
newdata.to_excel(compilation_folder+slash+'ThisStudy_and_2023_all_cols.xlsx')
LERZ2018.to_excel(compilation_folder+slash+'LERZ2018_all_cols.xlsx')
Lerner.to_excel(compilation_folder+slash+'Lerner_all_cols.xlsx')

### Create a simplified Dataframe with all data for plotting
- We create a Subframe which has all the data but only some of the columns needed (to avoid merge problems with literature data and having a giant dataframe)
- We do not include all the olivine chemistry aside from Fo content because not all have the same data the same way. Fo is consistent.

In [15]:
ME_cols=['Fo_Ol_%',
 'Na2O_Gl',
 'Al2O3_Gl',
 'P2O5_Gl',
 'CaO_Gl',
 'K2O_Gl',
 'TiO2_Gl',
 'SiO2_Gl',
 'MgO_Gl',
 'FeOt_Gl',
 'MnO_Gl',
 'Total_wt%_Gl',
 'Na2O_STD_Gl',
 'Al2O3_STD_Gl',
 'P2O5_STD_Gl',
 'CaO_STD_Gl',
 'K2O_STD_Gl',
 'TiO2_STD_Gl',
 'SiO2_STD_Gl',
 'MgO_STD_Gl',
 'FeOt_STD_Gl',
 'MnO_STD_Gl',
 '#of analyses (when averaged)_Gl',
 'non_numeric_column_behavior_used (First/Last instance kept or skipped)_Gl']

info_cols = ['Reference','Eruption_title','Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)',
'Sample Site: Longitude (WGS84)','Sample Site: Latitude (WGS84)',
'Sample','Sample_crystal','FI_name','FI_type','Fluid inclusion notes','decrepit',
'power (mW)',
'Spectral Center',
'Mag (X)'
]
ebsd_cols=['EBSDname+grainID_EBSDdata',
'GOS',
'Grain Size (pixels)',
'Grain Size (um2)',
'subBoundaryLength (um)',
'equivalentRadius (um)',
'GB Length/Sqrt Size',
'Total GB length']

ramanPD_cols=['Corrected_Splitting','Corrected_Splitting_σ','Density g/cm3','σ Density g/cm3','SO2 mol%',
                                          'XH2O_av_iteration3_final','SingleCalc_P_kbar','std_dev_MC_P_kbar','SingleCalc_D_km',
                                          'std_dev_MC_D_km','Temp_from_Fo_all','Temp_error']

all_data_simplified = pd.concat([newdata[info_cols+ramanPD_cols+ME_cols+ebsd_cols],
                               LERZ2018[info_cols+ramanPD_cols+ME_cols+ebsd_cols],
                               Lerner[info_cols+ramanPD_cols+ME_cols+ebsd_cols]])

all_data_simplified.to_excel(compilation_folder+slash+'all_data_simplified.xlsx')
all_data_simplified

,Reference,Eruption_title,"Eruption_location_type(ERZ,VSWRZ,SSWRZ,Summit)",Sample Site: Longitude (WGS84),Sample Site: Latitude (WGS84),Sample,Sample_crystal,FI_name,FI_type,Fluid inclusion notes,...,#of analyses (when averaged)_Gl,non_numeric_column_behavior_used (First/Last instance kept or skipped)_Gl,EBSDname+grainID_EBSDdata,GOS,Grain Size (pixels),Grain Size (um2),subBoundaryLength (um),equivalentRadius (um),GB Length/Sqrt Size,Total GB length
0,"Devitre et al. (2024, JPET)",IC\n(Sept 2023),Summit,-155.267850,19.407830,K23,K23_2,K23_2_FIA,P,NaN,...,NaN,NaN,NaN,0.112099,14847.0,9.574355e+05,465.517028,552.051785,3.820465,465.517028
1,this study,SSWRZ\n(Dec 1974),SSWRZ,-155.295217,19.380050,KL0920,KL0920_c216,KL0920_c216_a2_FID,P,Seems associated to growth clustering,...,NaN,NaN,NaN,0.364898,6337.0,1.181151e+06,1467.348586,613.165584,18.432806,1467.348586
2,this study,SSWRZ\n(June 2024),SSWRZ,-155.298120,19.375625,K24,K24_5,K24_5_FIA,P,NaN,...,NaN,NaN,K24_5_10_54,0.096661,5935.0,5.955962e+05,62.107255,435.412617,0.806180,62.107255
3,this study,Circ. flow\n(~1700),SSWRZ,-155.291070,19.383150,KL0921,KL0921_c288,KL0921_c288_a1_FIA,PS,NaN,...,5.0,skip,NaN,0.803403,13329.0,1.445071e+06,5790.460357,678.218566,50.155009,5790.460357
4,this study,Circ. flow\n(~1700),SSWRZ,-155.291070,19.383150,K21,K21_78b,K21_78b_FI#5,S,NaN,...,5.0,skip,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,"Lerner et al. (2024, EPSL)",Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,-155.292290,19.389810,K99-5,K99-5_11,K99-5_11b,P,Isolated fluid inclusion (vapor-phase),...,15.0,skip,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,"Lerner et al. (2024, EPSL)",Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,-155.292290,19.389810,K99-5,K99-5_11,K99-5_11c,P,Isolated fluid inclusion (vapor-phase),...,15.0,skip,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,"Lerner et al. (2024, EPSL)",Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,-155.292290,19.389810,K99-5,K99-5_11,K99-5_11e,P,Isolated fluid inclusion (vapor-phase),...,15.0,skip,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,"Lerner et al. (2024, EPSL)",Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,-155.292290,19.389810,K99-5,K99-5_11,K99-5_11f,P,Isolated fluid inclusion (vapor-phase),...,15.0,skip,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,"Lerner et al. (2024, EPSL)",Early Keanakākoʻi\n(1500-1650 CE),Explosive Era,-155.292290,19.389810,K99-5,K99-5_11,K99-5_11g,P,Isolated fluid inclusion (vapor-phase),...,15.0,skip,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN